django-invoice/django_invoice/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings

from django.conf.urls.static import static

from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls)
] 

urlpatterns += i18n_patterns(
    path('', include('fact_app.urls')),
)

if settings.DEBUG:

    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django-invoice/fact_app/urls.py
from django.urls import path
from . import views
from .views import update_article


urlpatterns = [ 
    path('', views.HomeView.as_view(), name='home'),
    
    path('', views.index, name='index'),
    path('delete-invoice/', views.delete_invoice, name='delete-invoice'),
    path('modify-invoice/', views.modify_invoice, name='modify-invoice'),
    path('delete-customer/<int:pk>', views.DeleteCustomerView.as_view() , name='delete_customer'),
    path('edit_customer/<int:pk>/', views.EditCustomerView.as_view(), name='edit_customer'),
    path('add-customer/',views.AddCustomerView.as_view(), name='add-customer'),
    path('add-invoice', views.AddInvoiceView.as_view(), name='add-invoice'),
    path('add-invoice2', views.AddInvoice2View.as_view(), name='add-invoice2'),
    path('view-invoice/<int:pk>', views.InvoiceVisualizationView.as_view(), name='view-invoice'),
    path('view-invoice2/<int:pk>', views.Invoice2VisualizationView.as_view(), name='view-invoice2'),
    path('invoice-pdf/<int:pk>', views.get_invoice_pdf, name="invoice-pdf"),
    path('invoice2-pdf/<int:pk>', views.get_invoice2_pdf, name="invoice2-pdf"),
    
    
    path('delete-article/<int:article_id>/', views.delete_article.as_view(), name='delete-article'),
    
    path('add-invoice3', views.AddInvoice3View.as_view(), name='add-invoice3'),
    path('update-article/<int:article_id>/', update_article, name='update_article'),
    path('delete-produit/<int:article_id>/', views.delete_produit, name='delete_produit'),
]

django-invoice/fact_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django import forms


class Customer(models.Model):
    name = models.CharField(max_length=132)
    email = models.EmailField()
    phone = models.CharField(max_length=132)
    address = models.CharField(max_length=64)
    city = models.CharField(max_length=32)
    created_date = models.DateTimeField(auto_now_add=True)
    save_by = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = "Customer"
        verbose_name_plural = "Customers"

    def __str__(self):
        return self.name


class Invoice(models.Model):
    INVOICE_TYPE = (
        ('R', _('RECEIPT')),
        ('P', _('PROFORMA INVOICE')),
        ('I', _('INVOICE'))
    )

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    code = models.CharField(max_length=32, default='DEFAULT_CODE')
    save_by = models.ForeignKey(User, on_delete=models.CASCADE)
    invoice_date_time = models.DateTimeField(auto_now_add=True)
    total = models.DecimalField(max_digits=10, decimal_places=3, default=0.000)
    prix_vente = models.DecimalField(max_digits=10, decimal_places=3, default=0.000)
    montant_ht = models.DecimalField(max_digits=10, decimal_places=3, default=0.000)
    montant_ttc = models.DecimalField(max_digits=10, decimal_places=3, default=0.000)
    last_updated_date = models.DateTimeField(null=True, blank=True)
    paid = models.BooleanField(default=False)
    invoice_type = models.CharField(max_length=1, choices=INVOICE_TYPE)
    comments = models.TextField(null=True, max_length=1000, blank=True)

    class Meta:
        verbose_name = "Invoice"
        verbose_name_plural = "Invoices"

    def __str__(self):
        date = self.invoice_date_time.date() if self.invoice_date_time else "Unknown Date"
        return f"{self.customer.name}_{date}"

    def update_total(self):
        articles = self.article_set.all()
        self.total = sum(article.total for article in articles)
        self.montant_ht = sum(article.montant_ht for article in articles)
        self.montant_ttc = sum(article.montant_ttc for article in articles)
        self.total_ht = sum(article.montant_ht for article in articles)
        self.total_ttc = sum(article.montant_ttc for article in articles)
        super().save()

    def get_total(self):
        return sum(article.total for article in self.article_set.all())


class Article(models.Model):
    invoice = models.ForeignKey(Invoice, null=True, blank=True, on_delete=models.CASCADE)
    code = models.CharField(max_length=32, default='DEFAULT_CODE')
    name = models.CharField(max_length=32)
    quantity = models.IntegerField()
    unit_price = models.DecimalField(max_digits=10, decimal_places=3, default=0.000)
    remise = models.DecimalField(max_digits=5, decimal_places=3, default=0)
    tva = models.DecimalField(max_digits=5, decimal_places=3, default=0.000)
    total = models.DecimalField(max_digits=10, decimal_places=3, editable=False, default=0.000)
    prix_vente = models.DecimalField(max_digits=10, decimal_places=3, default=0.000, editable=False)
    montant_ht = models.DecimalField(max_digits=10, decimal_places=3, default=0.000, editable=False)
    montant_ttc = models.DecimalField(max_digits=10, decimal_places=3, default=0.000, editable=False)
    prix = models.DecimalField(max_digits=10, decimal_places=3, default=0.000, editable=True)
    @property
    def total_tva(self):
        return self.montant_ttc - self.montant_ht

    class Meta:
        verbose_name = 'Article'
        verbose_name_plural = 'Articles'

    def save(self, *args, **kwargs):
        self.montant_ht = self.quantity * self.unit_price * (1 - self.remise / 100)
        self.montant_ttc = self.montant_ht * (1 + self.tva / 100)
        self.total_ht = sum(self.montant_ht)
        self.total_ttc = sum(self.montant_ttc)
        self.total_tva = self.total_ttc - self.total_ht
        self.total = self.quantity * self.unit_price  # Corrected to ensure it includes tax
        super().save(*args, **kwargs)
        self.invoice.update_total()
        

django-invoice/templates/article_form.html
<!-- fact_app/templates/fact_app/article_form.html -->
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Save</button>
</form>

django-invoice/templates/edit_article.html
{% extends "base.html" %}

{% block content %}
<h2>Edit Article</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-group">
        <label for="code">Code</label>
        <input type="number" name="code" class="form-control" id="code" value="{{ article.code }}">
    </div>
    <div class="form-group">
        <label for="name">Name</label>
        <input type="text" name="name" class="form-control" id="name" value="{{ article.name }}">
    </div>
    <div class="form-group">
        <label for="qty-1">Quantité</label>
        <input type="number" name="qty" class="form-control" id="qty" value="{{ article.quantity }}">
    </div>

    <div class="form-group">
        <label for="unit-1">Unit Price</label>
        <input type="number" name="unit" step="0.01" class="form-control" id="unit" value="{{ article.unit_price}}">
    </div>

    <button type="submit" class="btn btn-primary">Save changes</button>
</form>

{% endblock content %}


django-invoice/templates/index.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block content %}
<br><br>

<div class="d-flex flex-wrap justify-content-start">
   <div class="p-2">
     <a href="{% url 'add-invoice' %}" class="btn btn-primary">
       {% trans 'Enregistrer une nouvelle facture' %} <span class="badge text-bg-secondary"></span>
     </a>
 
     <a href="{% url 'add-invoice2' %}" class="btn btn-primary">
       {% trans 'Enregistrer une nouvelle bon de livraison' %} <span class="badge text-bg-secondary"></span>
     </a>
  
     <a href="{% url 'add-customer' %}" class="btn btn-primary">
       {% trans 'Enregistrez un nouveau client' %} <span class="badge text-bg-secondary"></span>
     </a>
   
     <a href="{% url 'add-invoice3' %}" class="btn btn-primary">
       {% trans 'Enregistrez un nouveau produit' %} <span class="badge text-bg-secondary"></span>
     </a>
   </div>
 </div>

<br><br>

<div class="form-group">
   <input id="search" class="form-control" type="text" placeholder="Rechercher....">
</div>

<div>
   <table class="table table-striped-columns">
      <thead>
         <tr>
            <th scope="col">#</th>
            <th scope="col">NOM CLIENT</th>
            <th scope="col">DATE</th>
            <th scope="col">TOTAL</th>
            <th scope="col">TYPE DE FACTURE</th>
            <th scope="col">ACTION</th>
         </tr>
      </thead>
      <tbody id="myTable">
         {% if invoices %}
         {% for facture in invoices %}
         <tr>
            <th scope="row">{{ forloop.counter0|add:invoices.start_index }}</th>
            <td>{{ facture.customer.name }}</td>
            <td>{{ facture.invoice_date_time|date:"d-m-Y" }}</td>
            <td>{{ facture.get_total }}</td>
            <td>{{ facture.get_invoice_type_display }}</td>
            <td>
               <a href="#" title="{% trans 'Detail' %}" class="btn btn-sm btn-primary" data-id="{{ facture.pk }}" data-type="{{ facture.invoice_type }}">{% trans 'View' %}</a>
               <button id="btn-invoice-sup" type="button" data-toggle="modal" data-target="#supprimer" class="badge text-white bg-danger" title="Supprimer" data-id="{{ facture.pk }}" data-customer="{{ facture.customer.name }}">{% trans 'Delete' %} </button>
            </td>
         </tr>
         {% endfor %}

         {% if invoices.has_other_pages %}
         <div class="btn-group" role="group" aria-label="Item pagination">
            {% if invoices.has_previous %}
            <a href="?page={{ invoices.previous_page_number }}" class="btn btn-outline-primary">&laquo;</a>
            {% endif %}

            {% for page_number in invoices.paginator.page_range %}
               {% if invoices.number == page_number %}
                  <button class="btn btn-outline-primary active">
                     <span> {{ page_number }} <span class="sr-only">(current)</span></span>
                  </button>
               {% else %}
                  <a href="?page={{ page_number }}" class="btn btn-outline-primary">
                     {{ page_number }}
                  </a>
               {% endif %}
            {% endfor %}

            {% if invoices.has_next %}
               <a href="?page={{ invoices.next_page_number }}" class="btn btn-outline-primary">&raquo;</a>
            {% endif %}
         </div>
         {% endif %}
         {% else %}
         <p class="text-center text-white">No invoice found.</p>
         {% endif %}
      </tbody>
   </table>
</div>

<!-- Modal suppression -->
<div class="modal fade" id="supprimer" tabindex="-1" role="dialog" aria-labelledby="sexampleModalLabel" aria-hidden="true">
   <div class="modal-dialog" role="document">
      <div class="modal-content">
         <div class="modal-header">
            <h5 class="modal-title text-dark" id="sexampleModalLabel">Delete Invoice</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
               <span aria-hidden="true">&times;</span>
            </button>
         </div>
         <div class="modal-body">
            <form method="post">
               {% csrf_token %}
               <input name="id_supprimer" type="hidden" id="id_supprimer">
               <label id="label_id_s" class="text-dark checkbox-inline"> <strong id="strong_id_s">Are you sure you want to delete the invoice?</strong></label>

               <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <button type="submit" class="btn btn-danger">Delete</button>
               </div>
            </form>
         </div>
      </div>
   </div>
</div>
<!-- end modal-->

<br><br>

<script type="text/javascript">
   // modification
   $(document).on('click', '#btn-invoice-mod', function() {
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_modified').val(invoice_id);
   })

   // deleting of invoice
   $(document).on('click', '#btn-invoice-sup', function() {
      let invoice_id = $(this).data('id');
      let customer = $(this).data('customer');
      $('#id_supprimer').val(invoice_id);
   })
</script>

<script>
   $(document).ready(function() {
      $("#search").on("keyup", function() {
         var value = $(this).val().toLowerCase();
         $("#myTable tr").filter(function() {
            $(this).toggle($(this).text().toLocaleLowerCase().indexOf(value) > -1)
         });
      });

      // View invoice
      $('.btn-primary').click(function() {
         var invoiceId = $(this).data('id');
         var invoiceType = $(this).data('type');
         if (invoiceType === 'BON DE LIVRAISON') {
            window.location.href = '{% url "view-invoice2" pk=0 %}'.replace('0', invoiceId);
         } else {
            window.location.href = '{% url "view-invoice" pk=0 %}'.replace('0', invoiceId);
         }
      });
   });
</script>

{% endblock %}

django-invoice/templates/invoice-pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
   <!-- bootstrap -->
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">




   <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
   <title>Facture</title>

   <style>

     body {
           color: #000; 
            margin: 0;
            padding: 0;
            font: 400 .875rem 'Open Sans', sans-serif;
            color: #bcd0f7;
            background-color: #f0f0f0;
            position: relative;
            height: 100%;
        }

        .invoice-container {
            padding: 1rem;
        }

        .invoice-container .invoice-header .invoice-logo {
            margin: 0.8rem 0 0 0;
            display: inline-block;
            font-size: 1.6rem;
            font-weight: 700;
            color: #bcd0f7;
        }

        .invoice-container .invoice-header .invoice-logo img {
            max-width: 130px;
        }

        .invoice-container .invoice-header address {
            font-size: 0.8rem;
            color: #8a99b5;
            margin: 0;
        }

        .invoice-container .invoice-details {
            margin: 1rem 0 0 0;
            padding: 1rem;
            line-height: 180%;
            background-color: #1a233a;
        }

        .invoice-container .invoice-details .invoice-num {
            text-align: right;
            font-size: 0.8rem;
        }

        .invoice-container .invoice-body {
            padding: 1rem 0 0 0;
        }

        .invoice-container .invoice-footer {
            text-align: center;
            font-size: 0.7rem;
            margin: 5px 0 0 0;
        }

        .invoice-status {
            text-align: center;
            padding: 1rem;
            background: #272e48;
            -webkit-border-radius: 4px;
            -moz-border-radius: 4px;
            border-radius: 4px;
            margin-bottom: 1rem;
        }

        .invoice-status h2.status {
            margin: 0 0 0.8rem 0;
        }

        .invoice-status h5.status-title {
            margin: 0 0 0.8rem 0;
            color: #8a99b5;
        }

        .invoice-status p.status-type {
            margin: 0.5rem 0 0 0;
            padding: 0;
            line-height: 150%;
        }

        .invoice-status i {
            font-size: 1.5rem;
            margin: 0 0 1rem 0;
            display: inline-block;
            padding: 1rem;
            background-color: #1a233a;
            -webkit-border-radius: 50px;
            -moz-border-radius: 50px;
            border-radius: 50px;
        }

        .invoice-status .badge {
            text-transform: uppercase;
        }

        @media (max-width: 767px) {
            .invoice-container {
                padding: 1rem;
            }
        }

        .card {
            background: #272E48;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            border: 0;
            margin-bottom: 1rem;
        }

        .custom-table {
            border: 1px solid #2b3958;
        }

        .custom-table thead {
            background-color: #0455b8;
        }

        .custom-table thead th {
            border: 0;
            color: #0b0b0b;
        }

        .custom-table>tbody tr:hover {
            background-color: #172033;
        }

        .custom-table>tbody tr:nth-of-type(even) {
            background-color: #1a243a;
        }

        .custom-table>tbody td {
            border: 1px solid #2e3d5f;
        }

        .table {
            background-color: #0b1326;
            color: #05070b;
            font-size: .75rem;
        }

        .text-success {
            color: #070800 !important;
        }

        .custom-actions-btns {
            margin: auto;
            display: flex;
            justify-content: flex-end;
        }

        .custom-actions-btns .btn {
            margin: .3rem 0 .3rem .3rem;
        }

   </style>
</head>
<body>

    <div class="container">
        <div class="row gutters">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                <div class="card">
                    <div class="card-body p-0">
                        <div class="invoice-container">
                            <div class="invoice-header">
        
                                <!-- Row start -->
                                <div class="row gutters">
                                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
                                        <a href="donaldprogrammeur.com" class="invoice-logo">
                                            Donald Programmer
                                        </a>
                                    </div>
                                    <div class="col-lg-6 col-md-6 col-sm-6">
                                        <address class="text-right">
                                            Donald Programmer Inc, 45 NorthWest<br>
                                            Cameroon, Douala<br>
                                            00000 00000
                                        </address>
                                    </div>
                                </div>
                                <!-- Row end -->
        
                                <!-- Row start -->
                                <div class="row gutters">
                                    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
                                        <div class="invoice-details">
                                            <address>
                                                {{obj.customer.name}}<br>
                                                {{obj.customer.address}}, {{obj.customer.city}}, Cameroon
                                            </address>
                                        </div>
                                    </div>
                                    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
                                        <div class="invoice-details">
                                            <div class="invoice-num">
                                                <div>{{obj.get_invoice_type_display}} - #00{{obj.id}}</div>
                                                <div>{{obj.invoice_date_time}}</div>
                                            </div>
                                        </div>													
                                    </div>
                                </div>
                                <!-- Row end -->
        
                            </div>
        
                            <div class="invoice-body">
        
                                <!-- Row start -->
                                <div class="row gutters">
                                    <div class="col-lg-12 col-md-12 col-sm-12">
                                        <div class="table-responsive">
                                            <table class="table custom-table m-0">
                                                <thead>
                                                    <tr>
                                                        <th>Items</th>
                                                        <th>Product ID</th>
                                                        <th>Quantities</th>
                                                        <th>Unit Price</th>
                                                        <th>Subtotal</th>
                                                    </tr>
                                                </thead>
                                                <tbody>
                                                  {% for article in articles %}  
                                                  
                                                    <tr>
    
                                                       
    
                                                        <td>
                                                            {{ article.name }}
                                                            
                                                        </td>
    
                                                        <td>
                                                            {{ article.id }}
                                                            
                                                        </td>
    
                                                        <td>
                                                            {{ article.quantity }}
                                                            
                                                        </td>
    
                                                        <td>
                                                            {{ article.unit_price }}
                                                            
                                                        </td>
    
                                                        <td>
                                                            {{ article.get_total }}
                                                            
                                                        </td>
    
                                                        
                                                        
                                                    </tr>
                                                   {% endfor %} 
                                                    
                                                    
                                                    <tr>
                                                        <td>Comment: {{obj.comments}}</td>
                                                        <td colspan="2">
                                                            <p>
                                                                Subtotal<br>
                                                                Shipment &amp; Handling<br>
                                                                Tax<br>
                                                            </p>
                                                            <h5 class="text-success"><strong>Total</strong></h5>
                                                        </td>			
                                                        <td>
                                                            <p>
                                                                {{obj.get_total}} FCFA<br>
                                                                00.00 FCFA<br>
                                                                00.00 FCFA<br>
                                                            </p>
                                                            <h5 class="text-success"><strong>{{obj.get_total}} FCFA</strong></h5>
                                                        </td>
                                                        <td> 
                                                                PAID:                    
    
                                                            {% if obj.paid  %}
    
                                                               <strong style="color: green;">YES</strong>
                                                            {% else %}
                                                                <strong style="color: red;">NO</strong>
       
                                                            {% endif %}
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </div>
                                <!-- Row end -->
        
                            </div>
        
                            <div class="invoice-footer">
                                Thank you for your purchase {{date}} .
                            </div>
        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    
    
</body>
</html>

django-invoice/templates/invoice-template.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<div class="container">
    <div class="row gutters">
    	<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
    		<div class="card">
    			<div class="card-body p-0">
    				<div class="invoice-container">
    					<div class="invoice-header">
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12">
    								<div class="custom-actions-btns mb-5">
    									<a href="" class="btn btn-primary">
    										<i class="icon-download"></i> Download
    									</a>
    									<a href="#" class="btn btn-secondary">
    										<i class="icon-printer"></i> Print
    									</a>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6">
    								<a href="donaldprogrammeur.com" class="invoice-logo">
    									Donald Programmer
    								</a>
    							</div>
    							<div class="col-lg-6 col-md-6 col-sm-6">
    								<address class="text-right">
    									Donald Programmer Inc, 45 NorthWest<br>
    									Cameroon, Douala<br>
    									00000 00000
    								</address>
    							</div>
    						</div>
    						<!-- Row end -->
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<address>
    										{{obj.customer.name}}<br>
    										{{obj.customer.address}}, {{obj.customer.city}}, Cameroon
    									</address>
    								</div>
    							</div>
    							<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    								<div class="invoice-details">
    									<div class="invoice-num">
    										<div>{{obj.get_invoice_type_display}} - #00{{obj.id}}</div>
    										<div>{{obj.invoice_date}}</div>
    									</div>
    								</div>													
    							</div>
    						</div>
    						<!-- Row end -->
    
    					</div>
    
    					<div class="invoice-body">
    
    						<!-- Row start -->
    						<div class="row gutters">
    							<div class="col-lg-12 col-md-12 col-sm-12">
    								<div class="table-responsive">
    									<table class="table custom-table m-0">
    										<thead>
    											<tr>
    												<th>Nom produit</th>
													<th>Product ID</th>
													<th>Quantité</th>
													<th>Prix unitaire</th>
													<th>Subtotal</th>
    											</tr>
    										</thead>
    										<tbody>
                                              {% for article in articles %}  
                                              
    											<tr>

                                                   

                                                    <td>
    													{{ article.name }}
    													
    												</td>

													<td>
    													{{ article.id }}
    													
    												</td>

													<td>
    													{{ article.quantite }}
    													
    												</td>

													<td>
    													{{ article.prix_u }}
    													
    												</td>

													<td>
    													{{ article.get_total }}
    													
    												</td>

                                                    
    												
    											</tr>
                                               {% endfor %} 
    											
    											
    											<tr>
    												<td>Comment: {{obj.comments}}</td>
    												<td colspan="2">
														<p>
															Subtotal<br>
															Shipment &amp; Handling<br>
															Tax<br>
														</p>
    													<h5 class="text-success"><strong>Total</strong></h5>
    												</td>			
    												<td>

    													<h5 class="text-success"><strong>${{obj.get_total}} FCFA</strong></h5>
    												</td>
                                                    <td> 
                                                            PAID:                    

                                                        {% if obj.paid  %}

                                                           <img class="icon" src="{% static 'images/icon-yes.svg' %}" alt="True">
                                                        {% else %}
                                                            <img class="icon" src="{% static 'images/icon-no.svg' %}" alt="False">
   
                                                        {% endif %}
                                                    </td>
    											</tr>
    										</tbody>
    									</table>
    								</div>
    							</div>
    						</div>
    						<!-- Row end -->
    
    					</div>
    
    					<div class="invoice-footer">
    						Thank you for your purchase .
    					</div>
    
    				</div>
    			</div>
    		</div>
    	</div>
    </div>
</div>

{% endblock content %}